apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      imagePullSecrets:
      - name: my-dockerhub-secret  # Reference the secret for Docker authentication
      containers:
      - name: sample-app
        image: barathkumar29/helloworld-python
        ports:
        - containerPort: 5000
